import re

def read(path):
    raw = open(path, "rb").read()
    crlf = b"\r\n" in raw
    return raw.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n"), crlf

def write(path, text, crlf):
    out = text.replace("\n", "\r\n") if crlf else text
    open(path, "wb").write(out.encode("utf-8"))

# ── STEP 1: Add translation keys to LanguageContext.tsx ──────────────────────
c, crlf = read("src/app/context/LanguageContext.tsx")

new_keys = {
    "en": {
        "trips.my_trips": "My Trips",
        "trips.upcoming": "Upcoming",
        "trips.past_stays": "Past Stays",
        "trips.no_trips": "No upcoming trips",
        "trips.no_trips_sub": "Time to explore Kenya",
        "trips.contact_host": "Contact Host",
        "trips.cancel_booking": "Cancel Booking",
        "trips.book_again": "Book Again",
        "trips.nights": "nights",
        "trips.guests": "guests",
        "trips.status_confirmed": "Confirmed",
        "trips.status_pending": "Pending",
        "trips.status_cancelled": "Cancelled",
        "messages.title": "Messages",
        "messages.no_messages": "No messages yet",
        "messages.no_messages_sub": "Your conversations will appear here",
        "messages.conversations": "conversations",
        "messages.conversation": "conversation",
        "messages.type_message": "Type a message...",
        "messages.send": "Send",
        "messages.call": "Call",
        "messages.conversation_not_found": "Conversation not found",
        "property.book_now": "Book Now",
        "property.per_night": "per night",
        "property.reviews": "Reviews",
        "property.amenities": "Amenities",
        "property.about_space": "About this space",
        "property.check_in": "Check in",
        "property.check_out": "Check out",
        "property.guests": "Guests",
        "property.total": "Total",
        "property.message_host": "Message Host",
        "property.instant_book": "Instant Book",
        "property.checking_stays": "Checking your stays",
        "property.hosted_by": "Hosted by",
        "property.member_since": "Member since",
        "property.cleaning_fee": "Cleaning fee",
        "property.service_fee": "Service fee",
        "host.dashboard": "Dashboard",
        "host.listings": "Listings",
        "host.bookings": "Bookings",
        "host.earnings": "Earnings",
        "host.add_listing": "Add Listing",
        "host.no_listings": "No listings yet",
        "host.no_bookings": "No bookings yet",
        "host.contact_guest": "Contact Guest",
        "host.approve": "Approve",
        "host.decline": "Decline",
        "host.total_earnings": "Total Earnings",
        "host.this_month": "This Month",
        "host.occupancy_rate": "Occupancy Rate",
        "host.profile": "Host Profile",
        "saved.title": "Saved",
        "saved.no_saved": "No saved properties yet",
        "saved.no_saved_sub": "Tap the heart icon to save properties",
        "payment.title": "Payment",
        "payment.confirm_booking": "Confirm Booking",
        "payment.pay_with_mpesa": "Pay with M-Pesa",
        "payment.enter_phone": "Enter M-Pesa phone number",
        "payment.processing": "Processing...",
        "common.loading": "Loading...",
        "common.back": "Back",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",
        "common.search": "Search",
        "common.filter": "Filter",
        "common.sort": "Sort",
        "common.share": "Share",
        "common.report": "Report",
        "common.edit": "Edit",
        "common.delete": "Delete",
        "common.view_all": "See all",
        "common.per_night": "/ night",
        "common.rating": "Rating",
        "common.location": "Location",
        "home.nearby_stays": "Nearby Stays",
        "home.top_rated": "Top Rated",
        "home.featured": "Featured",
        "home.no_top_rated": "No top rated properties yet",
        "home.good_morning": "Good morning",
        "home.good_afternoon": "Good afternoon",
        "home.good_evening": "Good evening",
    },
    "sw": {
        "trips.my_trips": "Safari Zangu",
        "trips.upcoming": "Zinazokuja",
        "trips.past_stays": "Mapumziko ya Awali",
        "trips.no_trips": "Hakuna safari zinazokuja",
        "trips.no_trips_sub": "Wakati wa kuchunguza Kenya",
        "trips.contact_host": "Wasiliana na Mwenyeji",
        "trips.cancel_booking": "Ghairi Uhifadhi",
        "trips.book_again": "Hifadhi Tena",
        "trips.nights": "usiku",
        "trips.guests": "wageni",
        "trips.status_confirmed": "Imethibitishwa",
        "trips.status_pending": "Inasubiri",
        "trips.status_cancelled": "Imeghairiwa",
        "messages.title": "Ujumbe",
        "messages.no_messages": "Hakuna ujumbe bado",
        "messages.no_messages_sub": "Mazungumzo yako yataonekana hapa",
        "messages.conversations": "mazungumzo",
        "messages.conversation": "mazungumzo",
        "messages.type_message": "Andika ujumbe...",
        "messages.send": "Tuma",
        "messages.call": "Piga Simu",
        "messages.conversation_not_found": "Mazungumzo hayakupatikana",
        "property.book_now": "Hifadhi Sasa",
        "property.per_night": "kwa usiku",
        "property.reviews": "Maoni",
        "property.amenities": "Huduma",
        "property.about_space": "Kuhusu nafasi hii",
        "property.check_in": "Ingia",
        "property.check_out": "Toka",
        "property.guests": "Wageni",
        "property.total": "Jumla",
        "property.message_host": "Tuma Ujumbe Mwenyeji",
        "property.instant_book": "Hifadhi Moja kwa Moja",
        "property.checking_stays": "Inakagua mapumziko yako",
        "property.hosted_by": "Ikiwa na mwenyeji",
        "property.member_since": "Mwanachama tangu",
        "property.cleaning_fee": "Ada ya usafi",
        "property.service_fee": "Ada ya huduma",
        "host.dashboard": "Dashibodi",
        "host.listings": "Orodha",
        "host.bookings": "Uhifadhi",
        "host.earnings": "Mapato",
        "host.add_listing": "Ongeza Orodha",
        "host.no_listings": "Hakuna orodha bado",
        "host.no_bookings": "Hakuna uhifadhi bado",
        "host.contact_guest": "Wasiliana na Mgeni",
        "host.approve": "Kubali",
        "host.decline": "Kataa",
        "host.total_earnings": "Jumla ya Mapato",
        "host.this_month": "Mwezi Huu",
        "host.occupancy_rate": "Kiwango cha Ukazi",
        "host.profile": "Wasifu wa Mwenyeji",
        "saved.title": "Zilizohifadhiwa",
        "saved.no_saved": "Hakuna mali zilizohifadhiwa bado",
        "saved.no_saved_sub": "Bonyeza moyo kuhifadhi mali",
        "payment.title": "Malipo",
        "payment.confirm_booking": "Thibitisha Uhifadhi",
        "payment.pay_with_mpesa": "Lipa na M-Pesa",
        "payment.enter_phone": "Weka nambari ya M-Pesa",
        "payment.processing": "Inashughulika...",
        "common.loading": "Inapakia...",
        "common.back": "Rudi",
        "common.save": "Hifadhi",
        "common.cancel": "Ghairi",
        "common.confirm": "Thibitisha",
        "common.search": "Tafuta",
        "common.filter": "Chuja",
        "common.sort": "Panga",
        "common.share": "Shiriki",
        "common.report": "Ripoti",
        "common.edit": "Hariri",
        "common.delete": "Futa",
        "common.view_all": "Ona yote",
        "common.per_night": "/ usiku",
        "common.rating": "Ukadiriaji",
        "common.location": "Mahali",
        "home.nearby_stays": "Mapumziko ya Karibu",
        "home.top_rated": "Yenye Ukadiriaji wa Juu",
        "home.featured": "Iliyoangaziwa",
        "home.no_top_rated": "Hakuna mali zenye ukadiriaji wa juu bado",
        "home.good_morning": "Habari za asubuhi",
        "home.good_afternoon": "Habari za mchana",
        "home.good_evening": "Habari za jioni",
    },
    "fr": {
        "trips.my_trips": "Mes Voyages",
        "trips.upcoming": "A venir",
        "trips.past_stays": "Sejours passes",
        "trips.no_trips": "Aucun voyage a venir",
        "trips.no_trips_sub": "Il est temps d'explorer le Kenya",
        "trips.contact_host": "Contacter l'hote",
        "trips.cancel_booking": "Annuler la reservation",
        "trips.book_again": "Reserver a nouveau",
        "trips.nights": "nuits",
        "trips.guests": "voyageurs",
        "trips.status_confirmed": "Confirme",
        "trips.status_pending": "En attente",
        "trips.status_cancelled": "Annule",
        "messages.title": "Messages",
        "messages.no_messages": "Aucun message pour l'instant",
        "messages.no_messages_sub": "Vos conversations apparaitront ici",
        "messages.conversations": "conversations",
        "messages.conversation": "conversation",
        "messages.type_message": "Ecrire un message...",
        "messages.send": "Envoyer",
        "messages.call": "Appeler",
        "messages.conversation_not_found": "Conversation introuvable",
        "property.book_now": "Reserver",
        "property.per_night": "par nuit",
        "property.reviews": "Avis",
        "property.amenities": "Equipements",
        "property.about_space": "A propos de cet espace",
        "property.check_in": "Arrivee",
        "property.check_out": "Depart",
        "property.guests": "Voyageurs",
        "property.total": "Total",
        "property.message_host": "Contacter l'hote",
        "property.instant_book": "Reservation immediate",
        "property.checking_stays": "Verification de vos sejours",
        "property.hosted_by": "Heberge par",
        "property.member_since": "Membre depuis",
        "property.cleaning_fee": "Frais de menage",
        "property.service_fee": "Frais de service",
        "host.dashboard": "Tableau de bord",
        "host.listings": "Annonces",
        "host.bookings": "Reservations",
        "host.earnings": "Revenus",
        "host.add_listing": "Ajouter une annonce",
        "host.no_listings": "Aucune annonce",
        "host.no_bookings": "Aucune reservation",
        "host.contact_guest": "Contacter le voyageur",
        "host.approve": "Approuver",
        "host.decline": "Refuser",
        "host.total_earnings": "Revenus totaux",
        "host.this_month": "Ce mois",
        "host.occupancy_rate": "Taux d'occupation",
        "host.profile": "Profil d'hote",
        "saved.title": "Enregistres",
        "saved.no_saved": "Aucun logement enregistre",
        "saved.no_saved_sub": "Appuyez sur le coeur pour enregistrer",
        "payment.title": "Paiement",
        "payment.confirm_booking": "Confirmer la reservation",
        "payment.pay_with_mpesa": "Payer avec M-Pesa",
        "payment.enter_phone": "Entrer le numero M-Pesa",
        "payment.processing": "Traitement...",
        "common.loading": "Chargement...",
        "common.back": "Retour",
        "common.save": "Sauvegarder",
        "common.cancel": "Annuler",
        "common.confirm": "Confirmer",
        "common.search": "Rechercher",
        "common.filter": "Filtrer",
        "common.sort": "Trier",
        "common.share": "Partager",
        "common.report": "Signaler",
        "common.edit": "Modifier",
        "common.delete": "Supprimer",
        "common.view_all": "Voir tout",
        "common.per_night": "/ nuit",
        "common.rating": "Note",
        "common.location": "Lieu",
        "home.nearby_stays": "Sejours a proximite",
        "home.top_rated": "Les mieux notes",
        "home.featured": "En vedette",
        "home.no_top_rated": "Aucun logement bien note",
        "home.good_morning": "Bonjour",
        "home.good_afternoon": "Bon apres-midi",
        "home.good_evening": "Bonsoir",
    },
    "es": {
        "trips.my_trips": "Mis Viajes",
        "trips.upcoming": "Proximos",
        "trips.past_stays": "Estancias pasadas",
        "trips.no_trips": "No hay viajes proximos",
        "trips.no_trips_sub": "Es hora de explorar Kenia",
        "trips.contact_host": "Contactar al anfitron",
        "trips.cancel_booking": "Cancelar reserva",
        "trips.book_again": "Reservar de nuevo",
        "trips.nights": "noches",
        "trips.guests": "huespedes",
        "trips.status_confirmed": "Confirmado",
        "trips.status_pending": "Pendiente",
        "trips.status_cancelled": "Cancelado",
        "messages.title": "Mensajes",
        "messages.no_messages": "Sin mensajes aun",
        "messages.no_messages_sub": "Tus conversaciones apareceran aqui",
        "messages.conversations": "conversaciones",
        "messages.conversation": "conversacion",
        "messages.type_message": "Escribe un mensaje...",
        "messages.send": "Enviar",
        "messages.call": "Llamar",
        "messages.conversation_not_found": "Conversacion no encontrada",
        "property.book_now": "Reservar",
        "property.per_night": "por noche",
        "property.reviews": "Resenas",
        "property.amenities": "Comodidades",
        "property.about_space": "Sobre este espacio",
        "property.check_in": "Entrada",
        "property.check_out": "Salida",
        "property.guests": "Huespedes",
        "property.total": "Total",
        "property.message_host": "Mensaje al anfitron",
        "property.instant_book": "Reserva instantanea",
        "property.checking_stays": "Comprobando estancias",
        "property.hosted_by": "Organizado por",
        "property.member_since": "Miembro desde",
        "property.cleaning_fee": "Tarifa de limpieza",
        "property.service_fee": "Tarifa de servicio",
        "host.dashboard": "Panel",
        "host.listings": "Anuncios",
        "host.bookings": "Reservas",
        "host.earnings": "Ganancias",
        "host.add_listing": "Agregar anuncio",
        "host.no_listings": "Sin anuncios",
        "host.no_bookings": "Sin reservas",
        "host.contact_guest": "Contactar huesped",
        "host.approve": "Aprobar",
        "host.decline": "Rechazar",
        "host.total_earnings": "Ganancias totales",
        "host.this_month": "Este mes",
        "host.occupancy_rate": "Tasa de ocupacion",
        "host.profile": "Perfil de anfitron",
        "saved.title": "Guardados",
        "saved.no_saved": "Sin propiedades guardadas",
        "saved.no_saved_sub": "Toca el corazon para guardar",
        "payment.title": "Pago",
        "payment.confirm_booking": "Confirmar reserva",
        "payment.pay_with_mpesa": "Pagar con M-Pesa",
        "payment.enter_phone": "Ingresa numero M-Pesa",
        "payment.processing": "Procesando...",
        "common.loading": "Cargando...",
        "common.back": "Atras",
        "common.save": "Guardar",
        "common.cancel": "Cancelar",
        "common.confirm": "Confirmar",
        "common.search": "Buscar",
        "common.filter": "Filtrar",
        "common.sort": "Ordenar",
        "common.share": "Compartir",
        "common.report": "Reportar",
        "common.edit": "Editar",
        "common.delete": "Eliminar",
        "common.view_all": "Ver todo",
        "common.per_night": "/ noche",
        "common.rating": "Calificacion",
        "common.location": "Ubicacion",
        "home.nearby_stays": "Estancias cercanas",
        "home.top_rated": "Mejor valorados",
        "home.featured": "Destacados",
        "home.no_top_rated": "Sin propiedades destacadas aun",
        "home.good_morning": "Buenos dias",
        "home.good_afternoon": "Buenas tardes",
        "home.good_evening": "Buenas noches",
    },
    "zh": {
        "trips.my_trips": "我的行程",
        "trips.upcoming": "即将到来",
        "trips.past_stays": "过去的住宿",
        "trips.no_trips": "没有即将到来的行程",
        "trips.no_trips_sub": "是时候探索肯尼亚了",
        "trips.contact_host": "联系房东",
        "trips.cancel_booking": "取消预订",
        "trips.book_again": "再次预订",
        "trips.nights": "晚",
        "trips.guests": "位客人",
        "trips.status_confirmed": "已确认",
        "trips.status_pending": "待处理",
        "trips.status_cancelled": "已取消",
        "messages.title": "消息",
        "messages.no_messages": "暂无消息",
        "messages.no_messages_sub": "您的对话将在此显示",
        "messages.conversations": "个对话",
        "messages.conversation": "个对话",
        "messages.type_message": "输入消息...",
        "messages.send": "发送",
        "messages.call": "通话",
        "messages.conversation_not_found": "未找到对话",
        "property.book_now": "立即预订",
        "property.per_night": "每晚",
        "property.reviews": "评价",
        "property.amenities": "设施",
        "property.about_space": "关于此空间",
        "property.check_in": "入住",
        "property.check_out": "退房",
        "property.guests": "客人",
        "property.total": "总计",
        "property.message_host": "给房东发消息",
        "property.instant_book": "即时预订",
        "property.checking_stays": "正在查询住宿",
        "property.hosted_by": "房东",
        "property.member_since": "加入于",
        "property.cleaning_fee": "清洁费",
        "property.service_fee": "服务费",
        "host.dashboard": "仪表板",
        "host.listings": "房源",
        "host.bookings": "预订",
        "host.earnings": "收入",
        "host.add_listing": "添加房源",
        "host.no_listings": "暂无房源",
        "host.no_bookings": "暂无预订",
        "host.contact_guest": "联系房客",
        "host.approve": "批准",
        "host.decline": "拒绝",
        "host.total_earnings": "总收入",
        "host.this_month": "本月",
        "host.occupancy_rate": "入住率",
        "host.profile": "房东资料",
        "saved.title": "已保存",
        "saved.no_saved": "暂无保存的房源",
        "saved.no_saved_sub": "点击心形图标保存房源",
        "payment.title": "付款",
        "payment.confirm_booking": "确认预订",
        "payment.pay_with_mpesa": "使用M-Pesa付款",
        "payment.enter_phone": "输入M-Pesa手机号",
        "payment.processing": "处理中...",
        "common.loading": "加载中...",
        "common.back": "返回",
        "common.save": "保存",
        "common.cancel": "取消",
        "common.confirm": "确认",
        "common.search": "搜索",
        "common.filter": "筛选",
        "common.sort": "排序",
        "common.share": "分享",
        "common.report": "举报",
        "common.edit": "编辑",
        "common.delete": "删除",
        "common.view_all": "查看全部",
        "common.per_night": "/ 晚",
        "common.rating": "评分",
        "common.location": "位置",
        "home.nearby_stays": "附近住宿",
        "home.top_rated": "高评分",
        "home.featured": "精选",
        "home.no_top_rated": "暂无高评分房源",
        "home.good_morning": "早上好",
        "home.good_afternoon": "下午好",
        "home.good_evening": "晚上好",
    },
    "ar": {
        "trips.my_trips": "رحلاتي",
        "trips.upcoming": "القادمة",
        "trips.past_stays": "الاقامات السابقة",
        "trips.no_trips": "لا توجد رحلات قادمة",
        "trips.no_trips_sub": "حان وقت استكشاف كينيا",
        "trips.contact_host": "التواصل مع المضيف",
        "trips.cancel_booking": "الغاء الحجز",
        "trips.book_again": "احجز مجددا",
        "trips.nights": "ليال",
        "trips.guests": "ضيوف",
        "trips.status_confirmed": "مؤكد",
        "trips.status_pending": "قيد الانتظار",
        "trips.status_cancelled": "ملغى",
        "messages.title": "الرسائل",
        "messages.no_messages": "لا توجد رسائل بعد",
        "messages.no_messages_sub": "ستظهر محادثاتك هنا",
        "messages.conversations": "محادثات",
        "messages.conversation": "محادثة",
        "messages.type_message": "اكتب رسالة...",
        "messages.send": "ارسال",
        "messages.call": "اتصال",
        "messages.conversation_not_found": "المحادثة غير موجودة",
        "property.book_now": "احجز الآن",
        "property.per_night": "في الليلة",
        "property.reviews": "التقييمات",
        "property.amenities": "المرافق",
        "property.about_space": "عن هذا المكان",
        "property.check_in": "تسجيل الوصول",
        "property.check_out": "تسجيل المغادرة",
        "property.guests": "الضيوف",
        "property.total": "المجموع",
        "property.message_host": "مراسلة المضيف",
        "property.instant_book": "حجز فوري",
        "property.checking_stays": "جارٍ التحقق من الاقامات",
        "property.hosted_by": "من قبل",
        "property.member_since": "عضو منذ",
        "property.cleaning_fee": "رسوم التنظيف",
        "property.service_fee": "رسوم الخدمة",
        "host.dashboard": "لوحة التحكم",
        "host.listings": "القوائم",
        "host.bookings": "الحجوزات",
        "host.earnings": "الارباح",
        "host.add_listing": "اضافة قائمة",
        "host.no_listings": "لا توجد قوائم",
        "host.no_bookings": "لا توجد حجوزات",
        "host.contact_guest": "التواصل مع الضيف",
        "host.approve": "موافقة",
        "host.decline": "رفض",
        "host.total_earnings": "اجمالي الارباح",
        "host.this_month": "هذا الشهر",
        "host.occupancy_rate": "معدل الاشغال",
        "host.profile": "ملف المضيف",
        "saved.title": "المحفوظات",
        "saved.no_saved": "لا توجد عقارات محفوظة",
        "saved.no_saved_sub": "اضغط على القلب لحفظ العقارات",
        "payment.title": "الدفع",
        "payment.confirm_booking": "تاكيد الحجز",
        "payment.pay_with_mpesa": "الدفع بـ M-Pesa",
        "payment.enter_phone": "ادخل رقم M-Pesa",
        "payment.processing": "جارٍ المعالجة...",
        "common.loading": "جارٍ التحميل...",
        "common.back": "رجوع",
        "common.save": "حفظ",
        "common.cancel": "الغاء",
        "common.confirm": "تاكيد",
        "common.search": "بحث",
        "common.filter": "تصفية",
        "common.sort": "ترتيب",
        "common.share": "مشاركة",
        "common.report": "الابلاغ",
        "common.edit": "تعديل",
        "common.delete": "حذف",
        "common.view_all": "عرض الكل",
        "common.per_night": "/ ليلة",
        "common.rating": "التقييم",
        "common.location": "الموقع",
        "home.nearby_stays": "الاقامات القريبة",
        "home.top_rated": "الاعلى تقييما",
        "home.featured": "المميزة",
        "home.no_top_rated": "لا توجد عقارات عالية التقييم",
        "home.good_morning": "صباح الخير",
        "home.good_afternoon": "مساء الخير",
        "home.good_evening": "مساء النور",
    },
    "hi": {
        "trips.my_trips": "मेरी यात्राएं",
        "trips.upcoming": "आगामी",
        "trips.past_stays": "पिछले प्रवास",
        "trips.no_trips": "कोई आगामी यात्रा नहीं",
        "trips.no_trips_sub": "केन्या का पता लगाने का समय",
        "trips.contact_host": "होस्ट से संपर्क करें",
        "trips.cancel_booking": "बुकिंग रद्द करें",
        "trips.book_again": "फिर से बुक करें",
        "trips.nights": "रातें",
        "trips.guests": "मेहमान",
        "trips.status_confirmed": "पुष्टि हुई",
        "trips.status_pending": "लंबित",
        "trips.status_cancelled": "रद्द",
        "messages.title": "संदेश",
        "messages.no_messages": "अभी कोई संदेश नहीं",
        "messages.no_messages_sub": "आपकी बातचीत यहां दिखेगी",
        "messages.conversations": "बातचीत",
        "messages.conversation": "बातचीत",
        "messages.type_message": "संदेश लिखें...",
        "messages.send": "भेजें",
        "messages.call": "कॉल",
        "messages.conversation_not_found": "बातचीत नहीं मिली",
        "property.book_now": "अभी बुक करें",
        "property.per_night": "प्रति रात",
        "property.reviews": "समीक्षाएं",
        "property.amenities": "सुविधाएं",
        "property.about_space": "इस जगह के बारे में",
        "property.check_in": "चेक इन",
        "property.check_out": "चेक आउट",
        "property.guests": "मेहमान",
        "property.total": "कुल",
        "property.message_host": "होस्ट को संदेश",
        "property.instant_book": "तुरंत बुक करें",
        "property.checking_stays": "प्रवास जांच रहे हैं",
        "property.hosted_by": "होस्ट",
        "property.member_since": "सदस्य से",
        "property.cleaning_fee": "सफाई शुल्क",
        "property.service_fee": "सेवा शुल्क",
        "host.dashboard": "डैशबोर्ड",
        "host.listings": "लिस्टिंग",
        "host.bookings": "बुकिंग",
        "host.earnings": "कमाई",
        "host.add_listing": "लिस्टिंग जोड़ें",
        "host.no_listings": "कोई लिस्टिंग नहीं",
        "host.no_bookings": "कोई बुकिंग नहीं",
        "host.contact_guest": "मेहमान से संपर्क",
        "host.approve": "स्वीकार करें",
        "host.decline": "अस्वीकार करें",
        "host.total_earnings": "कुल कमाई",
        "host.this_month": "इस महीने",
        "host.occupancy_rate": "अधिभोग दर",
        "host.profile": "होस्ट प्रोफाइल",
        "saved.title": "सहेजे गए",
        "saved.no_saved": "कोई सहेजी गई संपत्ति नहीं",
        "saved.no_saved_sub": "सहेजने के लिए दिल दबाएं",
        "payment.title": "भुगतान",
        "payment.confirm_booking": "बुकिंग पुष्टि करें",
        "payment.pay_with_mpesa": "M-Pesa से भुगतान करें",
        "payment.enter_phone": "M-Pesa नंबर दर्ज करें",
        "payment.processing": "प्रसंस्करण...",
        "common.loading": "लोड हो रहा है...",
        "common.back": "वापस",
        "common.save": "सहेजें",
        "common.cancel": "रद्द करें",
        "common.confirm": "पुष्टि करें",
        "common.search": "खोजें",
        "common.filter": "फ़िल्टर",
        "common.sort": "क्रमबद्ध करें",
        "common.share": "साझा करें",
        "common.report": "रिपोर्ट",
        "common.edit": "संपादित करें",
        "common.delete": "हटाएं",
        "common.view_all": "सभी देखें",
        "common.per_night": "/ रात",
        "common.rating": "रेटिंग",
        "common.location": "स्थान",
        "home.nearby_stays": "पास के प्रवास",
        "home.top_rated": "शीर्ष रेटेड",
        "home.featured": "विशेष",
        "home.no_top_rated": "अभी कोई शीर्ष रेटेड नहीं",
        "home.good_morning": "सुप्रभात",
        "home.good_afternoon": "नमस्ते",
        "home.good_evening": "शुभ संध्या",
    },
}

# Insert new keys into each language block in LanguageContext.tsx
for lang, keys in new_keys.items():
    for k, v in keys.items():
        if k not in c:
            # Find the closing of this language block
            marker = f"'agent.speaking': 'Speaking'," if lang == "en" else None
            # Generic: find last key in block and insert after it
            # Just append to translations object directly
            pass

# Simpler approach: find each language's last entry and add before closing brace
lines = c.split("\n")
new_lines = []
i = 0
while i < len(lines):
    line = lines[i]
    new_lines.append(line)
    # Detect end of a language block by looking for pattern: "  }," after translation keys
    for lang, keys in new_keys.items():
        # Find the agent.speaking line for each lang then insert after
        speaking_marker = "'agent.speaking'"
        if speaking_marker in line and i + 1 < len(lines) and "}" in lines[i+1]:
            # Insert all new keys for this lang
            for k, v in keys.items():
                if f"'{k}'" not in c:
                    new_lines.append(f"    '{k}': '{v}',")
            break
    i += 1

c = "\n".join(new_lines)
write("src/app/context/LanguageContext.tsx", c, crlf)
print("LanguageContext.tsx updated with new keys")

# ── STEP 2: Wire up pages ─────────────────────────────────────────────────────
IMPORT_LINE = "import { useLanguage } from '../context/LanguageContext.tsx';"
HOOK_LINE = "  const { t } = useLanguage();"

def add_lang_hook(path, replacements):
    c, crlf = read(path)

    # Add import if missing
    if "useLanguage" not in c:
        # Insert after last import line
        lines = c.split("\n")
        last_import = 0
        for idx, l in enumerate(lines):
            if l.startswith("import "):
                last_import = idx
        lines.insert(last_import + 1, IMPORT_LINE)
        c = "\n".join(lines)

    # Add hook if missing
    if "const { t } = useLanguage()" not in c:
        # Insert after the first const/let/useState inside the component
        lines = c.split("\n")
        for idx, l in enumerate(lines):
            if "const {" in l or "useState" in l:
                lines.insert(idx, HOOK_LINE)
                break
        c = "\n".join(lines)

    # Apply replacements
    for old, new in replacements.items():
        c = c.replace(old, new)

    write(path, c, crlf)
    print(f"Fixed: {path}")

# Trips.tsx
add_lang_hook("src/app/pages/Trips.tsx", {
    ">My Trips<": ">{t('trips.my_trips')}<",
    ">Upcoming<": ">{t('trips.upcoming')}<",
    ">Past Stays<": ">{t('trips.past_stays')}<",
    ">No upcoming trips<": ">{t('trips.no_trips')}<",
    ">Time to explore Kenya<": ">{t('trips.no_trips_sub')}<",
    ">Contact Host<": ">{t('trips.contact_host')}<",
    ">Cancel Booking<": ">{t('trips.cancel_booking')}<",
    ">Book Again<": ">{t('trips.book_again')}<",
})

# Messages.tsx
add_lang_hook("src/app/pages/Messages.tsx", {
    ">Messages<": ">{t('messages.title')}<",
    ">No messages yet<": ">{t('messages.no_messages')}<",
    "0 conversations": "{t('messages.no_messages')}",
    "conversation${conversations.length > 1 ? 's' : ''}": "` ${t('messages.conversations')}`",
})

# Conversation.tsx
add_lang_hook("src/app/pages/Conversation.tsx", {
    ">Conversation not found<": ">{t('messages.conversation_not_found')}<",
    'placeholder="Type a message..."': "placeholder={t('messages.type_message')}",
    ">Send<": ">{t('messages.send')}<",
    ">Call<": ">{t('messages.call')}<",
})

# PropertyDetail.tsx
add_lang_hook("src/app/pages/PropertyDetail.tsx", {
    ">Book Now<": ">{t('property.book_now')}<",
    ">Reviews<": ">{t('property.reviews')}<",
    ">Check in<": ">{t('property.check_in')}<",
    ">Check out<": ">{t('property.check_out')}<",
    ">About this space<": ">{t('property.about_space')}<",
    "Checking your stays": "{t('property.checking_stays')}",
    ">Message Host<": ">{t('property.message_host')}<",
    ">Instant Book<": ">{t('property.instant_book')}<",
    "Cleaning fee": "{t('property.cleaning_fee')}",
    "Service fee": "{t('property.service_fee')}",
    ">Amenities<": ">{t('property.amenities')}<",
    "Hosted by": "{t('property.hosted_by')}",
    "Member since": "{t('property.member_since')}",
})

# Saved.tsx
add_lang_hook("src/app/pages/Saved.tsx", {
    ">Saved<": ">{t('saved.title')}<",
    ">No saved properties yet<": ">{t('saved.no_saved')}<",
    "Tap the heart icon to save properties": "{t('saved.no_saved_sub')}",
})

# HostDashboard.tsx
add_lang_hook("src/app/pages/HostDashboard.tsx", {
    ">Dashboard<": ">{t('host.dashboard')}<",
    ">Listings<": ">{t('host.listings')}<",
    ">Bookings<": ">{t('host.bookings')}<",
    ">Earnings<": ">{t('host.earnings')}<",
    ">Total Earnings<": ">{t('host.total_earnings')}<",
    ">This Month<": ">{t('host.this_month')}<",
    ">Occupancy Rate<": ">{t('host.occupancy_rate')}<",
})

# HostListings.tsx
add_lang_hook("src/app/pages/HostListings.tsx", {
    ">Add Listing<": ">{t('host.add_listing')}<",
    ">No listings yet<": ">{t('host.no_listings')}<",
    ">Listings<": ">{t('host.listings')}<",
})

# HostBookings.tsx
add_lang_hook("src/app/pages/HostBookings.tsx", {
    ">Bookings<": ">{t('host.bookings')}<",
    ">No bookings yet<": ">{t('host.no_bookings')}<",
    ">Contact Guest<": ">{t('host.contact_guest')}<",
    ">Approve<": ">{t('host.approve')}<",
    ">Decline<": ">{t('host.decline')}<",
})

# Payment.tsx
add_lang_hook("src/app/pages/Payment.tsx", {
    ">Payment<": ">{t('payment.title')}<",
    ">Confirm Booking<": ">{t('payment.confirm_booking')}<",
    ">Pay with M-Pesa<": ">{t('payment.pay_with_mpesa')}<",
    "Enter M-Pesa phone number": "{t('payment.enter_phone')}",
    ">Processing...<": ">{t('payment.processing')}<",
})

print("\nAll pages updated.")
print("Run: grep -rn \"useLanguage\" src/app/pages/ | wc -l")
