import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'sw' | 'fr' | 'es' | 'zh' | 'ar' | 'hi';

export interface LanguageConfig {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageConfig[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.explore': 'Explore',
    'nav.favorites': 'Favorites',
    'nav.inbox': 'Inbox',
    'nav.profile': 'Profile',
    'nav.host': 'Host',
    'lang.select_language': 'Select Language',
    'auth.welcome_back': 'Welcome back',
    'auth.sign_in_to_account': 'Sign in to your LALA account',
    'auth.continue_with_google': 'Continue with Google',
    'auth.or_continue_with': 'or continue with',
    'auth.email': 'Email',
    'auth.phone': 'Phone',
    'auth.password': 'Password',
    'auth.full_name': 'Full Name',
    'auth.email_address': 'Email Address',
    'auth.phone_number': 'Phone Number',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot password?',
    'auth.sign_in': 'Sign In',
    'auth.create_account': 'Create free account',
    'auth.back_to_home': '← Back to home',
    'auth.join_lala_kenya': 'Join LALA Kenya',
    'auth.back': 'Back',
    'auth.how_use_lala': 'How do you want to use LALA Kenya?',
    'auth.which_account_signing': 'Which account are you signing in to?',
    'auth.im_guest': 'I\'m a Guest',
    'auth.find_book_stays': 'Find and book amazing stays.',
    'auth.sign_in_guest': 'Sign in to guest account',
    'auth.im_host': 'I\'m a Host',
    'auth.list_space_earn': 'List your space and earn money.',
    'auth.sign_in_host': 'Sign in to host dashboard',
    'auth.new_to_lala': 'New to LALA?',
    'auth.sign_up': 'Sign Up',
    'auth.continue_as_guest': 'Continue as Guest',
    'profile.personal_info': 'Personal Information',
    'profile.login_security': 'Login & Security',
    'profile.payment_methods': 'Payment Methods',
    'profile.notifications': 'Notifications',
    'profile.help_center': 'Help Center',
    'profile.terms_policies': 'Terms & Policies',
    'agent.listening': 'Listening...',
    'agent.thinking': 'Thinking...',
    'agent.speaking': 'Speaking',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  sw: {
    'nav.home': 'Nyumbani',
    'nav.explore': 'Chunguza',
    'nav.favorites': 'Vipendwa',
    'nav.inbox': 'Inboksi',
    'nav.profile': 'Wasifu',
    'nav.host': 'Mwenyeji',
    'lang.select_language': 'Chagua Lugha',
    'auth.welcome_back': 'Karibu tena',
    'auth.sign_in_to_account': 'Ingia kwenye akaunti yako ya LALA',
    'auth.continue_with_google': 'Endelea na Google',
    'auth.or_continue_with': 'au endelea na',
    'auth.email': 'Barua pepe',
    'auth.phone': 'Simu',
    'auth.password': 'Nenosiri',
    'auth.full_name': 'Jina Kamili',
    'auth.email_address': 'Anwani ya Barua pepe',
    'auth.phone_number': 'Nambari ya Simu',
    'auth.remember_me': 'Kumbuka',
    'auth.forgot_password': 'Umesahau nenosiri?',
    'auth.sign_in': 'Ingia',
    'auth.create_account': 'Unde akaunti ya bure',
    'auth.back_to_home': '← Rudi nyumbani',
    'auth.join_lala_kenya': 'Jiunge na LALA Kenya',
    'auth.back': 'Rudi',
    'auth.how_use_lala': 'Unataka kutumia LALA Kenya vipi?',
    'auth.which_account_signing': 'Unaweza kuingia kwenye akaunti gani?',
    'auth.im_guest': 'Mimi ni Mgeni',
    'auth.find_book_stays': 'Tafuta na weka nafasi za ajabu.',
    'auth.sign_in_guest': 'Ingia kwenye akaunti ya mgeni',
    'auth.im_host': 'Mimi ni Mwenyeji',
    'auth.list_space_earn': 'Orodhesha nafasi yako na pesa.',
    'auth.sign_in_host': 'Ingia kwenye dashibodi ya mwenyeji',
    'auth.new_to_lala': 'Mpya katika LALA?',
    'auth.sign_up': 'Jiunge',
    'auth.continue_as_guest': 'Endelea kama Mgeni',
    'profile.personal_info': 'Maelezo ya Kibinafsi',
    'profile.login_security': 'Kuingia na Usalama',
    'profile.payment_methods': 'Njia za Malipo',
    'profile.notifications': 'Arifa',
    'profile.help_center': 'Kituo cha Msaada',
    'profile.terms_policies': 'Masharti na Sera',
    'agent.listening': 'Inasikiliza...',
    'agent.thinking': 'Inafikiri...',
    'agent.speaking': 'Inazungumza',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.explore': 'Explorer',
    'nav.favorites': 'Favoris',
    'nav.inbox': 'Boîte de réception',
    'nav.profile': 'Profil',
    'nav.host': 'Hôte',
    'lang.select_language': 'Sélectionner la langue',
    'auth.welcome_back': 'Bon retour',
    'auth.sign_in_to_account': 'Connectez-vous à votre compte LALA',
    'auth.continue_with_google': 'Continuer avec Google',
    'auth.or_continue_with': 'ou continuer avec',
    'auth.email': 'Email',
    'auth.phone': 'Téléphone',
    'auth.password': 'Mot de passe',
    'auth.full_name': 'Nom complet',
    'auth.email_address': 'Adresse email',
    'auth.phone_number': 'Numéro de téléphone',
    'auth.remember_me': 'Se souvenir de moi',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.sign_in': 'Se connecter',
    'auth.create_account': 'Créer un compte gratuit',
    'auth.back_to_home': '← Retour à l\'accueil',
    'auth.join_lala_kenya': 'Rejoindre LALA Kenya',
    'auth.back': 'Retour',
    'auth.how_use_lala': 'Comment voulez-vous utiliser LALA Kenya?',
    'auth.which_account_signing': 'À quel compte vous connectez-vous?',
    'auth.im_guest': 'Je suis un Invité',
    'auth.find_book_stays': 'Trouvez et réservez des séjours incroyables.',
    'auth.sign_in_guest': 'Connectez-vous au compte invité',
    'auth.im_host': 'Je suis un Hôte',
    'auth.list_space_earn': 'Listez votre espace et gagnez de l\'argent.',
    'auth.sign_in_host': 'Connectez-vous au tableau de bord hôte',
    'auth.new_to_lala': 'Nouveau sur LALA?',
    'auth.sign_up': 'S\'inscrire',
    'auth.continue_as_guest': 'Continuer en tant qu\'invité',
    'profile.personal_info': 'Informations Personnelles',
    'profile.login_security': 'Connexion & Sécurité',
    'profile.payment_methods': 'Méthodes de Paiement',
    'profile.notifications': 'Notifications',
    'profile.help_center': 'Centre d\'aide',
    'profile.terms_policies': 'Termes & Politiques',
    'agent.listening': 'Écoute...',
    'agent.thinking': 'Réflexion...',
    'agent.speaking': 'Parle',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.explore': 'Explorar',
    'nav.favorites': 'Favoritos',
    'nav.inbox': 'Bandeja de entrada',
    'nav.profile': 'Perfil',
    'nav.host': 'Anfitrión',
    'lang.select_language': 'Seleccionar idioma',
    'auth.welcome_back': 'Bienvenido de nuevo',
    'auth.sign_in_to_account': 'Inicia sesión en tu cuenta LALA',
    'auth.continue_with_google': 'Continuar con Google',
    'auth.or_continue_with': 'o continuar con',
    'auth.email': 'Correo electrónico',
    'auth.phone': 'Teléfono',
    'auth.password': 'Contraseña',
    'auth.full_name': 'Nombre completo',
    'auth.email_address': 'Dirección de correo',
    'auth.phone_number': 'Número de teléfono',
    'auth.remember_me': 'Recordarme',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.sign_in': 'Iniciar sesión',
    'auth.create_account': 'Crear cuenta gratuita',
    'auth.back_to_home': '← Volver al inicio',
    'auth.join_lala_kenya': 'Unirse a LALA Kenya',
    'auth.back': 'Volver',
    'auth.how_use_lala': '¿Cómo quieres usar LALA Kenya?',
    'auth.which_account_signing': '¿A qué cuenta estás accediendo?',
    'auth.im_guest': 'Soy un Invitado',
    'auth.find_book_stays': 'Busca y reserva estancias increíbles.',
    'auth.sign_in_guest': 'Acceder a cuenta de invitado',
    'auth.im_host': 'Soy un Anfitrión',
    'auth.list_space_earn': 'Lista tu espacio y gana dinero.',
    'auth.sign_in_host': 'Acceder al panel de anfitrión',
    'auth.new_to_lala': '¿Nuevo en LALA?',
    'auth.sign_up': 'Registrarse',
    'auth.continue_as_guest': 'Continuar como invitado',
    'profile.personal_info': 'Información Personal',
    'profile.login_security': 'Inicio de Sesión & Seguridad',
    'profile.payment_methods': 'Métodos de Pago',
    'profile.notifications': 'Notificaciones',
    'profile.help_center': 'Centro de Ayuda',
    'profile.terms_policies': 'Términos y Políticas',
    'agent.listening': 'Escuchando...',
    'agent.thinking': 'Pensando...',
    'agent.speaking': 'Hablando',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  zh: {
    'nav.home': '首页',
    'nav.explore': '探索',
    'nav.favorites': '收藏',
    'nav.inbox': '收件箱',
    'nav.profile': '个人资料',
    'nav.host': '房东',
    'lang.select_language': '选择语言',
    'auth.welcome_back': '欢迎回来',
    'auth.sign_in_to_account': '登录您的LALA账户',
    'auth.continue_with_google': '使用Google继续',
    'auth.or_continue_with': '或继续使用',
    'auth.email': '邮箱',
    'auth.phone': '电话',
    'auth.password': '密码',
    'auth.full_name': '全名',
    'auth.email_address': '邮箱地址',
    'auth.phone_number': '电话号码',
    'auth.remember_me': '记住我',
    'auth.forgot_password': '忘记密码?',
    'auth.sign_in': '登录',
    'auth.create_account': '创建免费账户',
    'auth.back_to_home': '← 返回首页',
    'auth.join_lala_kenya': '加入LALA Kenya',
    'auth.back': '返回',
    'auth.how_use_lala': '你想如何使用LALA Kenya？',
    'auth.which_account_signing': '你要登录哪个账户？',
    'auth.im_guest': '我是客人',
    'auth.find_book_stays': '查找并预订精彩的住宿。',
    'auth.sign_in_guest': '登录客人账户',
    'auth.im_host': '我是房东',
    'auth.list_space_earn': '列出您的空间并赚钱。',
    'auth.sign_in_host': '登录房东仪表板',
    'auth.new_to_lala': 'LALA新手？',
    'auth.sign_up': '注册',
    'auth.continue_as_guest': '以客人身份继续',
    'profile.personal_info': '个人信息',
    'profile.login_security': '登录与安全',
    'profile.payment_methods': '付款方式',
    'profile.notifications': '通知',
    'profile.help_center': '帮助中心',
    'profile.terms_policies': '条款与政策',
    'agent.listening': '正在听...',
    'agent.thinking': '正在想...',
    'agent.speaking': '正在说',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.explore': 'استكشف',
    'nav.favorites': 'المفضلة',
    'nav.inbox': 'البريد الوارد',
    'nav.profile': 'الملف الشخصي',
    'nav.host': 'المضيف',
    'lang.select_language': 'اختر اللغة',
    'auth.welcome_back': 'مرحباً بعودتك',
    'auth.sign_in_to_account': 'سجل الدخول إلى حساب LALA الخاص بك',
    'auth.continue_with_google': 'متابعة باستخدام Google',
    'auth.or_continue_with': 'أو المتابعة باستخدام',
    'auth.email': 'البريد الإلكتروني',
    'auth.phone': 'الهاتف',
    'auth.password': 'كلمة المرور',
    'auth.full_name': 'الاسم الكامل',
    'auth.email_address': 'عنوان البريد الإلكتروني',
    'auth.phone_number': 'رقم الهاتف',
    'auth.remember_me': 'تذكرني',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.sign_in': 'تسجيل الدخول',
    'auth.create_account': 'إنشاء حساب مجاني',
    'auth.back_to_home': '← العودة إلى الرئيسية',
    'auth.join_lala_kenya': 'انضم إلى LALA Kenya',
    'auth.back': 'العودة',
    'auth.how_use_lala': 'كيف تريد استخدام LALA Kenya؟',
    'auth.which_account_signing': 'أي حساب تقوم بتسجيل الدخول إليه؟',
    'auth.im_guest': 'أنا ضيف',
    'auth.find_book_stays': 'ابحث واحجز إقامات رائعة.',
    'auth.sign_in_guest': 'تسجيل الدخول إلى حساب الضيف',
    'auth.im_host': 'أنا مضيف',
    'auth.list_space_earn': 'ادرج مساحتك واربح المال.',
    'auth.sign_in_host': 'تسجيل الدخول إلى لوحة تحكم المضيف',
    'auth.new_to_lala': 'جديد في LALA؟',
    'auth.sign_up': 'التسجيل',
    'auth.continue_as_guest': 'المتابعة كضيف',
    'profile.personal_info': 'المعلومات الشخصية',
    'profile.login_security': 'تسجيل الدخول والأمان',
    'profile.payment_methods': 'طرق الدفع',
    'profile.notifications': 'الإشعارات',
    'profile.help_center': 'مركز المساعدة',
    'profile.terms_policies': 'الشروط والسياسات',
    'agent.listening': 'يستمع...',
    'agent.thinking': 'يفكر...',
    'agent.speaking': 'يتحدث',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
  hi: {
    'nav.home': 'होम',
    'nav.explore': 'एक्सप्लोर',
    'nav.favorites': 'पसंदीदा',
    'nav.inbox': 'इनबॉक्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.host': 'होस्ट',
    'lang.select_language': 'भाषा चुनें',
    'auth.welcome_back': 'वापसी पर स्वागत है',
    'auth.sign_in_to_account': 'अपने LALA खाते में साइन इन करें',
    'auth.continue_with_google': 'Google के साथ जारी रखें',
    'auth.or_continue_with': 'या जारी रखें',
    'auth.email': 'ईमेल',
    'auth.phone': 'फोन',
    'auth.password': 'पासवर्ड',
    'auth.full_name': 'पूरा नाम',
    'auth.email_address': 'ईमेल पता',
    'auth.phone_number': 'फोन नंबर',
    'auth.remember_me': 'मुझे याद रखें',
    'auth.forgot_password': 'पासवर्ड भूल गए?',
    'auth.sign_in': 'साइन इन',
    'auth.create_account': 'मुफ्त खाता बनाएं',
    'auth.back_to_home': '← होम पर वापस जाएं',
    'auth.join_lala_kenya': 'LALA Kenya से जुड़ें',
    'auth.back': 'वापस',
    'auth.how_use_lala': 'आप LALA Kenya का उपयोग कैसे करना चाहते हैं?',
    'auth.which_account_signing': 'आप किस खाते में साइन इन कर रहे हैं?',
    'auth.im_guest': 'मैं एक मेहमान हूँ',
    'auth.find_book_stays': 'शानदार ठहरावे ढूंढें और बुक करें।',
    'auth.sign_in_guest': 'मेहमान खाते में साइन इन करें',
    'auth.im_host': 'मैं एक होस्ट हूँ',
    'auth.list_space_earn': 'अपनी जगह सूचीबद्ध करें और पैसे कमाएं।',
    'auth.sign_in_host': 'होस्ट डैशबोर्ड में साइन इन करें',
    'auth.new_to_lala': 'LALA पर नए हैं?',
    'auth.sign_up': 'साइन अप करें',
    'auth.continue_as_guest': 'मेहमान के रूप में जारी रखें',
    'profile.personal_info': 'व्यक्तिगी जानकारी',
    'profile.login_security': 'लॉगिन और सुरक्षा',
    'profile.payment_methods': 'भुगतानी के तरीके',
    'profile.notifications': 'सूचनाएं',
    'profile.help_center': 'सहायता केंद्र',
    'profile.terms_policies': 'नियम और नीतियां',
    'agent.listening': 'सुन रहे हैं...',
    'agent.thinking': 'सोच रहे हैं...',
    'agent.speaking': 'बोल रहे हैं',
    'trips.my_trips': 'My Trips',
    'trips.upcoming': 'Upcoming',
    'trips.past_stays': 'Past Stays',
    'trips.no_trips': 'No upcoming trips',
    'trips.no_trips_sub': 'Time to explore Kenya',
    'trips.contact_host': 'Contact Host',
    'trips.cancel_booking': 'Cancel Booking',
    'trips.book_again': 'Book Again',
    'trips.nights': 'nights',
    'trips.guests': 'guests',
    'trips.status_confirmed': 'Confirmed',
    'trips.status_pending': 'Pending',
    'trips.status_cancelled': 'Cancelled',
    'messages.title': 'Messages',
    'messages.no_messages': 'No messages yet',
    'messages.no_messages_sub': 'Your conversations will appear here',
    'messages.conversations': 'conversations',
    'messages.conversation': 'conversation',
    'messages.type_message': 'Type a message...',
    'messages.send': 'Send',
    'messages.call': 'Call',
    'messages.conversation_not_found': 'Conversation not found',
    'property.book_now': 'Book Now',
    'property.per_night': 'per night',
    'property.reviews': 'Reviews',
    'property.amenities': 'Amenities',
    'property.about_space': 'About this space',
    'property.check_in': 'Check in',
    'property.check_out': 'Check out',
    'property.guests': 'Guests',
    'property.total': 'Total',
    'property.message_host': 'Message Host',
    'property.instant_book': 'Instant Book',
    'property.checking_stays': 'Checking your stays',
    'property.hosted_by': 'Hosted by',
    'property.member_since': 'Member since',
    'property.cleaning_fee': 'Cleaning fee',
    'property.service_fee': 'Service fee',
    'host.dashboard': 'Dashboard',
    'host.listings': 'Listings',
    'host.bookings': 'Bookings',
    'host.earnings': 'Earnings',
    'host.add_listing': 'Add Listing',
    'host.no_listings': 'No listings yet',
    'host.no_bookings': 'No bookings yet',
    'host.contact_guest': 'Contact Guest',
    'host.approve': 'Approve',
    'host.decline': 'Decline',
    'host.total_earnings': 'Total Earnings',
    'host.this_month': 'This Month',
    'host.occupancy_rate': 'Occupancy Rate',
    'host.profile': 'Host Profile',
    'saved.title': 'Saved',
    'saved.no_saved': 'No saved properties yet',
    'saved.no_saved_sub': 'Tap the heart icon to save properties',
    'payment.title': 'Payment',
    'payment.confirm_booking': 'Confirm Booking',
    'payment.pay_with_mpesa': 'Pay with M-Pesa',
    'payment.enter_phone': 'Enter M-Pesa phone number',
    'payment.processing': 'Processing...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view_all': 'See all',
    'common.per_night': '/ night',
    'common.rating': 'Rating',
    'common.location': 'Location',
    'home.nearby_stays': 'Nearby Stays',
    'home.top_rated': 'Top Rated',
    'home.featured': 'Featured',
    'home.no_top_rated': 'No top rated properties yet',
    'home.good_morning': 'Good morning',
    'home.good_afternoon': 'Good afternoon',
    'home.good_evening': 'Good evening',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguageConfig: LanguageConfig;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('lala-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lala-language', language);
  }, [language]);

  const t = (key: string): string => {
    const langTranslations = translations[language];
    return langTranslations?.[key] || key;
  };

  const currentLanguageConfig = LANGUAGES.find(lang => lang.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageConfig }}>
      {children}
    </LanguageContext.Provider>
  );
};
